import enum
from typing import Literal

type RawFormat = Literal["json", "xml"]
type RangeMode = Literal["after", "before", "between"]


class BaseStrEnum(enum.StrEnum):
    @classmethod
    def _missing_(cls, value: object) -> BaseStrEnum: ...
    
    @enum.property
    def lowercase(self) -> str: ...
    
    @enum.property
    def private(self) -> str: ...


class FormatEnum(BaseStrEnum):
    JSON = ...
    XML = ...


class EndpointEnum(BaseStrEnum):
    IPC = ...
    UF = ...
    USD = ...
    EURO = ...
    UTM = ...


class ModeEnum(BaseStrEnum):
    AFTER = ...
    BEFORE = ...
    BETWEEN = ...
