from __future__ import annotations

from cl_forge.rest.cmf.models.base import InterestRateCollection, InterestRateRecord


class TipRecord(InterestRateRecord): ...
class TipCollection(InterestRateCollection[TipRecord]): ...


class TmcRecord(InterestRateRecord): ...
class TmcCollection(InterestRateCollection[TmcRecord]): ...
