from __future__ import annotations

from cl_forge.rest.cmf.models.base import RateCollection, RateRecord


class TipRecord(RateRecord): ...
class TipCollection(RateCollection[TipRecord]): ...


class TmcRecord(RateRecord): ...
class TmcCollection(RateCollection[TmcRecord]): ...
