from __future__ import annotations

from abc import ABC, abstractmethod
from collections.abc import Sequence
from pathlib import Path
from typing import TYPE_CHECKING, ClassVar

# Pydantic requires `SecretStr` to be imported from the top level for it to
# work properly, so we can't import it within the `TYPE_CHECKING` block, even
# though it's only used in type annotations. This applies to pydantic's models
# (`BaseModel` and `BaseSettings`) and dataclasses.
from pydantic import SecretStr  # noqa: TC002
from pydantic.dataclasses import dataclass
from pydantic_settings import BaseSettings, SettingsConfigDict

if TYPE_CHECKING:
    from .enums import CredentialScope


__all__ = ("ApiKeyCredentials", "ApiKeySettings", "CredentialsProvider", "DotenvType",)


DotenvType = Path | str | Sequence[Path | str]


@dataclass(frozen=True, slots=True)
class CredentialsProvider(ABC):
    """Abstract base class for credentials providers."""

    prefix: ClassVar[str] = "CLFORGE_"
    """Root prefix for environment variables and .env files keys."""

    @abstractmethod
    def resolve(self, scope: CredentialScope) -> ApiKeyCredentials:
        """
        Abstract method to resolve credentials for a given scope.

        Each concrete implementation of :class:`CredentialsProvider` must
        implement this method to provide the logic for retrieving the API
        key based on the specified scope (e.g., from environment variables,
        .env files, etc.).
        """
        ...

    def _env_prefix(self, scope: CredentialScope) -> str:
        """
        Helper method to construct the environment variable prefix
        based on the scope, which is given by the API client.

        Returns
        -------
        str
            The constructed environment variable prefix for the given scope.
        """
        return f"{self.prefix}{scope.name}_"


@dataclass(frozen=True, slots=True)
class ApiKeyCredentials:
    """
    Model for holding API key credentials.
    
    Credential providers must always return an instance of this class from their
    `resolve` method, which ensures a consistent interface for accessing the API
    key across different providers.
    """

    api_key: SecretStr
    """API key to be used for API client authentication."""

    @property
    def value(self) -> str:
        """
        Returns the API key value as a string.

        This is a convenience property to access the API key value directly
        without having to call `.get_secret_value()` on the `SecretStr`
        instance every time.
        """
        return self.api_key.get_secret_value()


class ApiKeySettings(BaseSettings):
    """
    Settings for API key credentials.

    Meant to be used internally by credential providers that would benefit
    from pydantic's `BaseSettings` ability for loading attributes from
    different sources (e.g., environment variables, .env files, etc.).

    Notes
    -----
    - The `env_prefix` is dynamically set by the credential providers based on
      the scope.

    - Attribute names defined in this class must match whatever comes after the
      prefix in the environment variables or .env files.

    - Pydantic's `BaseSettings` class is case-insensitive by default, and we
      maintain this behavior, allowing the `api_key` attribute to be defined
      in lowercase within this class, while the corresponding environment
      variables can be defined in either uppercase or lowercase
      (e.g., `CLFORGE_CMF_API_KEY` or `clforge_cmf_api_key`).
    """

    model_config = SettingsConfigDict(
        # We set `extra="ignore"` to allow for flexibility in the input data
        # and prevent validation errors due to unexpected fields, which is
        # especially useful when loading from environment variables or .env
        # files that may contain other unrelated variables.
        extra="ignore",

        # Ignore env variables where value is an empty string. This isn't
        # valid for API keys.
        env_ignore_empty=True,

        # We excplicitly set the encoding because pydantic's default is `None`.
        env_file_encoding="utf-8",
    )

    api_key: SecretStr
    """API key to be used for API client authentication."""

    # We rely on `__init__` instead of `model_config` for dynamic `ApiKeySettings`
    # initialization for making it more explicit, easier to understand and type-safer.

    # This also overrides the default `__init__` generated by `BaseSettings`, so
    # only the parameters we explicitly define here are accepted, which prevents
    # potential issues with unexpected parameters being passed to the constructor
    # (e.g., `ApiKeySettings(_env_ignore_empty=False)` or any other parameter
    # defined in `BaseSettings` or `SettingsConfigDict` won't work).
    def __init__(self, *, env_prefix: str, env_file: DotenvType | None = None) -> None:
        """
        Initializes the API key settings with the given environment variable prefix
        and optional .env file path.

        Parameters
        ----------
        env_prefix : str
            The prefix to be used for environment variables when loading the API key.
        env_file : DotenvType, optional
            The path to the .env file from which to load the API key. If not provided
            or `None` (default), no .env file will be used, and the API key will only
            be loaded from environment variables.
        """
        super().__init__(_env_prefix=env_prefix, _env_file=env_file)
