from __future__ import annotations

from typing import TYPE_CHECKING, Any, Literal, Protocol, overload

if TYPE_CHECKING:
    from cl_forge.core.types import RawFormat


class CmfTransport(Protocol):
    @property
    def base_url(self) -> str: ...

    @property
    def api_key(self) -> str: ...

    @overload
    def get(self, path: str, fmt: Literal["json"] = ... ) -> dict[str, Any]: ...
    @overload
    def get(self, path: str, fmt: Literal["xml"]) -> str: ...
    @overload
    def get(self, path: str, fmt: RawFormat = ...) -> dict[str, Any] | str: ...
    
    def get(self, path: str, fmt: RawFormat = "json") -> dict[str, Any] | str: ...

    @overload
    async def aget(self, path: str, fmt: Literal["json"] = ... ) -> dict[str, Any]: ...
    @overload
    async def aget(self, path: str, fmt: Literal["xml"]) -> str: ...
    @overload
    async def aget(self, path: str, fmt: RawFormat = ...) -> dict[str, Any] | str: ...
    
    async def aget(self, path: str, fmt: RawFormat = "json") -> dict[str, Any] | str: ...
